name: flutter_qiniu
description: A flutter plugin for uploading files to Qiniu，support single image or multiple image uploads.
version: 0.1.4
author: ChuGuimin <icodd.cn@gmail.com>
homepage: https://github.com/GuiminChu/flutter_qiniu.git

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: cn.fg.flutter_qiniu
        pluginClass: FlutterQiniuPlugin
      ios:
        pluginClass: FlutterQiniuPlugin
